"""
Saved itinerary model.

Stores user-generated itineraries with sharing and export capabilities.
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import Column, String, Integer, JSON, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.database import Base


class SavedItinerary(Base):
    """
    Saved travel itinerary model.

    Stores complete itinerary data generated by the RAG pipeline,
    including destination, duration, and detailed day-by-day plans.
    Supports sharing via unique tokens and export to various formats.
    """

    __tablename__ = "saved_itineraries"

    # Primary key
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Foreign key to user
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True
    )

    # Itinerary metadata
    title = Column(String(255), nullable=True)
    destination = Column(String(255), nullable=False, index=True)
    duration_days = Column(Integer, nullable=False)

    # Full itinerary data from RAG pipeline
    # Structure: {
    #   "destination": "Bangkok",
    #   "duration_days": 5,
    #   "days": [...],
    #   "metadata": {...}
    # }
    itinerary_data = Column(JSON, nullable=False)

    # User notes
    notes = Column(Text, nullable=True)

    # Sharing settings
    is_public = Column(Boolean, nullable=False, default=False)
    share_token = Column(String(64), unique=True, nullable=True, index=True)
    share_expires_at = Column(DateTime(timezone=True), nullable=True)

    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        nullable=False,
        default=lambda: datetime.now(timezone.utc),
        index=True
    )
    updated_at = Column(
        DateTime(timezone=True),
        nullable=True,
        onupdate=lambda: datetime.now(timezone.utc)
    )

    # Relationships
    user = relationship("User", back_populates="itineraries")

    def __repr__(self):
        return f"<SavedItinerary(id={self.id}, destination={self.destination}, user_id={self.user_id})>"
